# Lint to ensure prettier and eslint are happy on develop
name: Lint

on:
  # Runs on pushes and pull requests targeting the develop branch
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
  HUSKY: 0

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run linters
        uses: Smithsonian/lint-action@0a3df23aad875996b93bd03f81213e3fca52fb04
        with:
          eslint: true
          prettier: true
          vue_tsc: true
