# Deploy Vite SSG site to Pages. Based on the GitHub Nuxt example:
# https://github.com/actions/starter-workflows/blob/main/pages/nuxtjs.yml
name: Deploy Vite SSG to Pages

on:
  # Runs on pushes targeting the develop branch
  push:
    branches: ['develop']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# Cancel in-progress runs to deploy as quickly as possible, since we're not deploying to prod.
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
      - name: Setup Pages
        id: setup_pages
        uses: actions/configure-pages@v5
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            dist
            .vite-ssg-temp
            components.d.ts
          key: ${{ runner.os }}-vite-ssg-build-${{ hashFiles('src') }}
          restore-keys: |
            ${{ runner.os }}-vite-ssg-build-
      - name: Install dependencies
        run: npm ci
      - name: Static HTML export with Vite SSG
        run: npm run build -- --base=${{ steps.setup_pages.outputs.base_path }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
  # Deploy job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
